# Generated by Django 4.1.6 on 2023-03-03 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Returned', 'Returned'), ('Maintainance', 'Maintainance'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Available', max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalouge.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.shop')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.tax_and_quantity')),
            ],
        ),
    ]
