# Generated by Django 4.1.6 on 2023-02-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_branch'),
        ('catalouge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.branch'),
            preserve_default=False,
        ),
    ]
