# Generated by Django 4.1.6 on 2023-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
