# Generated by Django 4.1.6 on 2023-02-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_role'),
        ('catalouge', '0002_remove_product_shop_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.shop'),
            preserve_default=False,
        ),
    ]
