# Generated by Django 4.1.6 on 2023-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0002_product_quantity_product_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Returned', 'Returned'), ('Maintainance', 'Maintainance'), ('Picked Up', 'Picked Up')], default='Available', max_length=100),
        ),
    ]
