# Generated by Django 4.1.6 on 2023-02-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0003_alter_product_branch_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
