# Generated by Django 4.1.6 on 2023-02-12 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(blank=True, choices=[('ShopAdmin', 'ShopAdmin'), ('Manager', 'ShopManager'), ('Staff', 'ShopStaff')], default='ShopStaff', max_length=255, null=True)),
                ('cover_photo', models.ImageField(blank=True, default='/default/seller-profile.jpg', null=True, upload_to='seller/cover_photo')),
                ('banner', models.ImageField(blank=True, default='/default/seller-profile.jpg', null=True, upload_to='seller/banner')),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('license', models.ImageField(upload_to='seller/license')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('num_of_reviews', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=50, null=True)),
                ('reg_no', models.CharField(max_length=50, null=True)),
                ('gst', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('policy', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=10)),
                ('order_number', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Pending', 'Pending')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=36)),
                ('signature_id', models.CharField(max_length=128)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.shop'),
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
