# Generated by Django 4.1.6 on 2023-02-03 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cover_photo', models.ImageField(blank=True, default='/default/seller-profile.jpg', null=True, upload_to='seller/cover_photo')),
                ('banner', models.ImageField(blank=True, default='/default/seller-profile.jpg', null=True, upload_to='seller/banner')),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('license', models.ImageField(upload_to='seller/license')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('num_of_reviews', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=50, null=True)),
                ('reg_no', models.CharField(max_length=50, null=True)),
                ('gst', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('policy', models.TextField(null=True)),
                ('about', models.TextField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
