# Generated by Django 4.1.6 on 2023-02-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0002_remove_product_shop_product_seller'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
