# Generated by Django 4.1.6 on 2023-02-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=10)),
                ('order_number', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Pending', 'Pending')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=36)),
                ('signature_id', models.CharField(max_length=128)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
            ],
        ),
    ]
