# Generated by Django 4.1.6 on 2023-03-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_tax_and_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax_and_quantity',
            name='tax_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tax_and_quantity',
            name='tax_percentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
