# Generated by Django 4.1.6 on 2023-02-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_seller_shop_delete_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='about',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='license',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='long',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='num_of_reviews',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='reg_no',
        ),
    ]
