# Generated by Django 4.1.6 on 2023-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='role',
            field=models.CharField(blank=True, choices=[('ShopAdmin', 'ShopAdmin'), ('Manager', 'ShopManager'), ('Staff', 'ShopStaff')], default='ShopStaff', max_length=255, null=True),
        ),
    ]
