# Generated by Django 4.1.6 on 2023-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_shop_seller_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='role',
            field=models.CharField(blank=True, choices=[('ShopOwner', 'ShopOwner'), ('Manager', 'ShopManager'), ('Staff', 'ShopStaff')], default='ShopStaff', max_length=255, null=True),
        ),
    ]
