# Generated by Django 4.1.6 on 2023-02-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_shop_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='seller',
        ),
        migrations.AddField(
            model_name='seller',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.shop'),
            preserve_default=False,
        ),
    ]
