# Generated by Django 4.1.6 on 2023-02-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_address_address_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Seller'), (2, 'Customer'), (3, 'Affliate'), (4, 'Affliate'), (5, 'Manager')], null=True),
        ),
    ]
