# Generated by Django 4.1.6 on 2023-02-14 04:26

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalouge', '__first__'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobilenumber', models.CharField(max_length=100)),
                ('alternatenumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('alternateNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalAmount', models.PositiveIntegerField()),
                ('amountPaid', models.PositiveIntegerField()),
                ('amountDue', models.PositiveIntegerField()),
                ('orderNo', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=6, max_length=6, prefix='', unique=True)),
                ('referenceNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Returned', 'Returned')], default='Booked', max_length=100)),
                ('products', models.ManyToManyField(to='catalouge.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.shop')),
            ],
            options={
                'permissions': [('user_create_booking', 'Can create bookings'), ('user_update_booking', 'Can update bookings'), ('user_delete_booking', 'Can delete bookings'), ('user_view_booking', 'Can view bookings')],
            },
        ),
        migrations.CreateModel(
            name='BookedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalouge.product')),
            ],
        ),
    ]
