# Generated by Django 4.1.6 on 2023-03-03 11:02

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '__first__'),
        ('catalouge', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobilenumber', models.CharField(max_length=500)),
                ('whatsappNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('startTime', models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Evening')], max_length=15)),
                ('endTime', models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Evening')], max_length=15)),
                ('endDate', models.DateField()),
                ('totalAmount', models.PositiveIntegerField()),
                ('amountPaid', models.PositiveIntegerField()),
                ('amountDue', models.IntegerField()),
                ('subtotal_price', models.PositiveIntegerField(null=True)),
                ('subtotal_tax', models.PositiveIntegerField(null=True)),
                ('discount', models.PositiveIntegerField(default=0, null=True)),
                ('orderNo', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=6, max_length=21, prefix='', unique=True)),
                ('referenceNo', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Returned', 'Returned'), ('Maintainance', 'Maintainance'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled')], default='Booked', max_length=500)),
                ('final_paid', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.customer')),
                ('products', models.ManyToManyField(to='catalouge.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.seller')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.shop')),
            ],
            options={
                'permissions': [('user_create_booking', 'Can create bookings'), ('user_update_booking', 'Can update bookings'), ('user_delete_booking', 'Can delete bookings'), ('user_view_booking', 'Can view bookings')],
            },
        ),
        migrations.CreateModel(
            name='BookedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=500)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalouge.product')),
            ],
        ),
    ]
