# Generated by Django 4.1.6 on 2023-02-24 09:20

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedproduct',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookedproduct',
            name='price',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookedproduct',
            name='size',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bookedproduct',
            name='status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='orderNo',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=6, max_length=21, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='referenceNo',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Returned', 'Returned'), ('Maintainance', 'Maintainance')], default='Booked', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobilenumber',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsappNumber',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
