# Generated by Django 4.1.6 on 2023-03-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproduct',
            name='tax',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.tax_and_quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookedproduct',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
