# Generated by Django 4.1.6 on 2023-02-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('user_create_booking', 'Can create bookings'), ('user_update_booking', 'Can update bookings'), ('user_delete_booking', 'Can delete bookings'), ('user_view_booking', 'Can view bookings')]},
        ),
    ]
