# Generated by Django 4.1.6 on 2023-02-14 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='alternateNumber',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='mobileNumber',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.customer'),
            preserve_default=False,
        ),
    ]
