# Generated by Django 4.1.6 on 2023-02-03 08:15

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('catalouge', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('mobileNumber', models.CharField(max_length=100)),
                ('alternateNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('totalAmount', models.PositiveIntegerField()),
                ('amountPaid', models.PositiveIntegerField()),
                ('amountDue', models.PositiveIntegerField()),
                ('orderNo', shortuuid.django_fields.ShortUUIDField(alphabet=None, db_index=True, editable=False, length=6, max_length=6, prefix='', unique=True)),
                ('referenceNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booking', 'Borrowed'), ('Not Available', 'Not Available'), ('Returned', 'Returned')], default='Borrowed', max_length=100)),
                ('products', models.ManyToManyField(to='catalouge.product')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.shop')),
            ],
        ),
        migrations.CreateModel(
            name='BookedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalouge.product')),
            ],
        ),
    ]
