# Generated by Django 4.1.6 on 2023-02-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('booking', '0002_booking_discount_alter_booking_amountdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.branch'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seller.seller'),
        ),
    ]
