# Generated by Django 4.1.6 on 2023-02-14 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_branch'),
        ('booking', '0002_remove_booking_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='shop',
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.branch'),
            preserve_default=False,
        ),
    ]
