# Generated by Django 4.1.6 on 2023-02-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_bookedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Not Available', 'Not Available'), ('Returned', 'Returned')], default='Booked', max_length=100),
        ),
    ]
