# Generated by Django 4.1.6 on 2023-02-13 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_role'),
        ('booking', '0002_alter_booking_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Seller',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='booking',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.shop'),
        ),
    ]
