# Generated by Django 4.1.6 on 2023-02-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_role'),
        ('booking', '0003_rename_seller_booking_seller_booking_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.shop'),
        ),
    ]
