# Generated by Django 4.1.6 on 2023-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_branch_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_paid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
