# Generated by Django 4.1.6 on 2023-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_shop_booking_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='endTime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Afternoon', 'Afternoon')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='startTime',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Afternoon', 'Afternoon')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
