# Generated by Django 4.1.6 on 2023-02-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternatenumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
