# Generated by Django 4.1.6 on 2023-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_final_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedproduct',
            name='status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='endTime',
            field=models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Evening')], max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='startTime',
            field=models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Evening')], max_length=15),
        ),
    ]
